
  export const ORDER_REQUESTED = 'ORDER_REQUESTED';
  export const ORDER_RECEIVED = 'ORDER_RECEIVED';
  export const ORDER_REQUEST_FAILED = 'ORDER_REQUEST_FAILED';
  export const ORDER_SUBMIT_REQUESTED = 'ORDER_SUMIT_REQUESTED';
  export const ORDER_SUBMITTED = 'ORDER_SUBMITTED';
  export const ORDER_SUBMIT_FAILED = 'ORDER_SUBMIT_FAILED';
  export const ORDER_UPDATE = 'ORDER_UPDATE';
